### ISSUE TITLE
lookup voorbeeld werkt niet

### ISSUE THREAD

**Issue by bertt** [PDOK/locatieserver#1]
op pagina https://github.com/PDOK/locatieserver/wiki/Zoekvoorbeelden-Locatieserver
staat het lookup voorbeeld:
```
http://geodata.nationaalgeoregister.nl/locatieserver/lookup?wt=xml&id=adr-2009603
```
maar die geeft niks terug. Kan dat aangepast worden?

**Comment by fsteggink** [comment]
Bert, bedankt voor het melden. Ik heb de documentatie zojuist bijgewerkt.
