### ISSUE TITLE
source code?

### ISSUE THREAD

**Issue by bertt** [PDOK/locatieserver#2]
waar is de source code van deze server te vinden?

**Comment by fsteggink** [comment]
De code en configuratie is van de Politie overgenomen. Hiervoor is een overeenkomst tussen PDOK/Kadaster en Politie getekend. Het open source maken van deze oplossing maakt hier geen onderdeel van uit.

Ik zou dat zelf graag anders hebben gezien, want ik denk dat juist het openbaar maken hiervan een goede boost zou zijn voor de ontwikkeling van Locatieserver. Er zijn nog wat zaken die beter zouden kunnen, zoals de sortering van de resultaten en het ontbreken van de OpenLS interface, wat heel goed in samenspraak kan met de open source community.

**Comment by fsteggink** [comment]
Zie ook https://pdokforum.geonovum.nl/t/wensen-locatieserver/260/3?u=pdokbeheer
